import { useCallback, useEffect, useState } from "react";
import { _get, _post } from "../../utils/ApiService";
import { Page, ErrorBox, buttonClass } from "../../components/Operations/common";

const payload = (r) => r.data.results.data;
const tone = (n) => Number(n) ? "text-red-700" : "text-emerald-700";
export default function GovernanceIndex() {
    const [overview,setOverview]=useState(null),[cases,setCases]=useState([]),[policies,setPolicies]=useState([]),[credentials,setCredentials]=useState([]),[reviews,setReviews]=useState([]),[metrics,setMetrics]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
    const load=useCallback(async()=>{setError("");try{const results=await Promise.all(["overview","cases","policies","credentials","ai-reviews","metrics"].map(x=>_get(`/api/governance/${x}`)));[setOverview,setCases,setPolicies,setCredentials,setReviews,setMetrics].forEach((fn,i)=>fn(payload(results[i])))}catch(e){setError(e.response?.data?.message||"Unable to load governance workspace")}},[]);
    useEffect(()=>{load()},[load]);
    const runChecks=async()=>{setBusy(true);try{await _post("/api/governance/data-quality/run");await load()}catch(e){setError(e.response?.data?.message||"Checks could not be run")}finally{setBusy(false)}};
    const evidence=async()=>{setBusy(true);try{const data=payload(await _get("/api/governance/evidence-pack"));const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=`caremonitor-evidence-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(url)}catch(e){setError(e.response?.data?.message||"Evidence pack could not be created")}finally{setBusy(false)}};
    const cards=overview?[["Open quality cases",overview.quality.open,overview.quality.overdue+" overdue"],["Active policies",overview.policies.active,overview.policies.due+" reviews due"],["Credential alerts",Number(overview.credentials.expired)+Number(overview.credentials.expiring),overview.credentials.expired+" expired"],["AI reviews pending",overview.ai.pending,"human decision required"]]:[];
    return <Page title="Governance and quality" description="Auditable quality registers, workforce assurance, human-reviewed assistance and defined operational metrics.">
        <ErrorBox error={error}/><div className="flex flex-wrap gap-3"><button className={buttonClass} disabled={busy} onClick={runChecks}>Run data-quality checks</button><button className={buttonClass} disabled={busy} onClick={evidence}>Download evidence pack</button></div>
        <div className="grid gap-3 md:grid-cols-4">{cards.map(([k,v,h])=><div className="rounded-xl border bg-white p-4" key={k}><p className="text-xs text-gray-500">{k}</p><p className="mt-2 text-2xl font-semibold">{v}</p><p className={`text-xs ${tone(String(h).split(" ")[0])}`}>{h}</p></div>)}</div>
        {overview?.lastDataQualityRun&&<section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Latest data-quality result: {overview.lastDataQualityRun.status}</h2><p className="text-xs text-gray-500">{new Date(overview.lastDataQualityRun.createdAt).toLocaleString()}</p><ul className="mt-3 space-y-1 text-sm">{overview.lastDataQualityRun.findings.map(x=><li key={x.key} className={tone(x.count)}>{x.key.replaceAll("_"," ")}: {x.count} ({x.status})</li>)}</ul></section>}
        <div className="grid gap-5 xl:grid-cols-2"><Table title="Quality cases" heads={["Title","Kind","Severity","Status","Due"]} rows={cases.map(x=>[x.title,x.kind,x.severity,x.status,x.due_at?new Date(x.due_at).toLocaleDateString():"—"])} empty="No quality cases recorded."/><Table title="Policy register" heads={["Policy","Version","Status","Review","Acknowledged"]} rows={policies.map(x=>[x.title,x.version,x.status,x.review_at||"—",x.acknowledgements])} empty="No policies recorded."/><Table title="Staff credentials" heads={["Staff","Credential","Expiry","Status"]} rows={credentials.map(x=>[x.staffName,x.kind,x.expires_at||"—",x.displayStatus])} empty="No credentials recorded."/><Table title="AI review queue" heads={["Client","Type","Status","Created"]} rows={reviews.map(x=>[x.clientName,x.kind.replaceAll("_"," "),x.status,new Date(x.created_at).toLocaleDateString()])} empty="No suggestions awaiting review."/></div>
        <section className="rounded-xl border bg-white p-5"><h2 className="font-semibold">Metric dictionary</h2><p className="mb-3 text-xs text-gray-500">Every dashboard value must have a named owner and stable definition.</p>{metrics.map(x=><article key={x.metricKey} className="border-t py-3"><strong>{x.label}</strong><p className="text-sm">{x.definition}</p><small className="text-gray-500">Owner: {x.owner}</small></article>)}</section>
    </Page>;
}
function Table({title,heads,rows,empty}){return <section className="overflow-auto rounded-xl border bg-white p-5"><h2 className="mb-3 font-semibold">{title}</h2>{rows.length?<table className="w-full text-left text-sm"><thead><tr>{heads.map(h=><th className="p-2" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr className="border-t" key={i}>{r.map((v,j)=><td className="p-2" key={j}>{v}</td>)}</tr>)}</tbody></table>:<p className="text-sm text-gray-500">{empty}</p>}</section>}
