/** @type {import('tailwindcss').Config} */
import plugin from "tailwind-scrollbar-hide";

export default {
    content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                customNavy: "#0a1b32",
                customNavy1: "#182747",
                customNavy2: "#081028",
                customBlue: "#20bde7",
                customBlue1: "#3b82f6",
                customBlue2: "#3b82f6",
                customBlue3: "#2563eb",
                customRed: "#ef4444",
                customGreen: "#22c55e",
                customGrey: "#4b5563",
                customHoverGrey: "#f3f4f6",
                customHoverBlue: "#eff6ff",
                customTextGrey: "#374151",
                customTextGrey1: "#1f2937",
                customTextGrey2: "#9ca3af",
                customBorder: "#d1d5db",
                customDropdownBorder: "#1E817C",
                customDropdown: "#E6FAF8",
                customBgGrey: "#f8fafc",
                customCarerFeedBg: "#EFF3FB",
                customCalendarBg: "#bcc6d2",
                customActiveBg: "#1F3D7A",
                customTextColor: "#384735",
                customDefaultTextColor: "#3D4A5C",
                customTextNavy: "#1F3D7A",
                customBgLightBlue: "#F8FBFF",
                customTextDarkRed: "#6E0900",
                customBlack: "#29313D",
                customBlack1: "#444444",
                customGrey1: "#909090",
                customBgLightBlue1: "#F6F7F9",
                customTextLightNavy: "#1F3D7A",
                customFeedCardBg: "#EBFFEB",
                customFeedCardBg1: "#EBFFFB",
                customFeedCardGreenText: "#056205",
                customFeedCardBlueText: "#513A90",
                customFeedCardGreyText1: "#767676",
                customBgSandal: "#FADEA8",
                customDarkYellow: "#844F00",
                customBgLightYellow: "#FFFAF5",
                customCalenderBg: "#E0E5EBB3",
                customTableBg: "#E0E5EB",
                customGrey2: "#FAFAFA",
                customEventCardBorder: "#A50D01",
                customEventNotStartedCardBg: "#FFEDEC",
                customEventSheduleCardBg: "#FAF6FF",
                customEventSheduleCardBorder: "#3A1E6E",
                customBlack2: "#575D65",
                customBgDarkGrey: "#7F8691",
                customTextLightNavy1: "#0459B4",
                customInactiveBg: "#FBC6C4",
                customInactiveText: "#861914",
                customStatusActiveText: "#056205",
                customStatusActiveBg: "#A6EAA6",
                customGoldenBg: "#eec575",
                customGoldenText: "#855102",
                customOrangeBg: "#FFF2EB",
                customOrangeText: "#6A2F08",
                customGrey3: "#F3F3F3",
                customTealBg: "#316663",
                customDarkGreyBg: "#A3B0C2"
            },
            animation: {
                slideDown: "slideDown 0.3s ease-out",
            },
            keyframes: {
                slideDown: {
                    "0%": { transform: "translateY(-20px)", opacity: "0" },
                    "100%": { transform: "translateY(0)", opacity: "1" },
                },
            },
            fontFamily: {
                poppins: ["Poppins", "sans-serif"],
                signature: ['"Dancing Script"', 'cursive'],
            },
            boxShadow: {
                subtle: "0 0 4px rgba(30, 30, 30, 0.06)",
              }
              
        },
    },
    plugins: [plugin],
};
