export const SUPPORT_OPTIONS = [
    { label: "Administer", value: "ADMINISTER" },
    { label: "Assist", value: "ASSIST" },
    { label: "Prompt", value: "PROMPT" },
  ];
  
  export const TYPE_OPTIONS = [
    { label: "Scheduled", value: "SCHEDULED" },
    { label: "PRN", value: "PRN" },
    { label: "Blister pack", value: "BLISTER_PACK" },
  ];
  export const ROUTE_OPTIONS = [
    { label: "Select a route", value: "" },
    { label: "Arteriovenous fistula route", value: "ARTERIOVENOUS_FISTULA_ROUTE" },
    { label: "Auricular", value: "AURICULAR" },
    { label: "Body cavity", value: "BODY_CAVITY" },
    { label: "Buccal", value: "BUCCAL" },
    { label: "Caudal route", value: "CAUDAL_ROUTE" },
    { label: "Colostomy route", value: "COLOSTOMY_ROUTE" },
    { label: "Conjunctival route", value: "CONJUNCTIVAL_ROUTE" },
    { label: "Dental", value: "DENTAL" },
    { label: "Digestive tract route", value: "DIGESTIVE_TRACT_ROUTE" },
    { label: "Endocervical", value: "ENDOCERVICAL" },
    { label: "Endosinusial", value: "ENDOSSINUSIAL" },
    { label: "Endotracheopulmonary", value: "ENDOTRACHEOPULMONARY" },
    { label: "Epidural", value: "EPIDURAL" },
    { label: "Epilesional", value: "EPILESIONAL" },
    { label: "Epilesional route", value: "EPILESIONAL_ROUTE" },
    { label: "Extraamniotic", value: "EXTRAMNIOTIC" },
    { label: "Extracorporeal", value: "EXTRACORPOREAL" },
    { label: "Extracorporeal haemodialysis route", value: "EXTRACORPOREAL_HEMODIALYSIS_ROUTE" },
    { label: "Fistula route", value: "FISTULA_ROUTE" },
    { label: "Gastro-intestinal stoma route", value: "GASTRO_INTESTINAL_STOMA_ROUTE" },
    { label: "Gastroenteral", value: "GASTROENTERAL" },
    { label: "Gastrostomy route", value: "GASTROSTOMY_ROUTE" },
    { label: "Genito-urinary route", value: "GENITO_URINARY_ROUTE" },
    { label: "Gingival", value: "GINGIVAL" },
    { label: "Haemodiafiltration", value: "HEMODIAFILTRATION" },
    { label: "Haemodiafiltration route", value: "HEMODIAFILTRATION_ROUTE" },
    { label: "Haemodialysis", value: "HEMODIALYSIS" },
    { label: "Haemofiltration", value: "HEMOFILTRATION" },
    { label: "Ileostomy route", value: "ILEOSTOMY_ROUTE" },
    { label: "Implantation", value: "IMPLANTATION" },
    { label: "Infiltration", value: "INFILTRATION" },
    { label: "Inhalation", value: "INHALATION" },
    { label: "Interstitial route", value: "INTERSTITIAL_ROUTE" },
    { label: "Intracervical", value: "INTRACERVICAL" },
    { label: "Intracholangiopancreatic", value: "INTRACOLANGIOPANCREATIC" },
    { label: "Intracisternal route", value: "INTRACISTERNAL_ROUTE" },
    { label: "Intracolonic route", value: "INTRACOLONIC_ROUTE" },
    { label: "Intracorneal route", value: "INTRACORNEAL_ROUTE" },
    { label: "Intracoronal route", value: "INTRACORONAL_ROUTE" },
    { label: "Intradialytic", value: "INTRADIALYTIC" },
    { label: "Intradiscal", value: "INTRADISCAL" },
    { label: "Intraductal route", value: "INTRADUCTAL_ROUTE" },
    { label: "Intraduodenal route", value: "INTRADUODENAL_ROUTE" },
    { label: "Intradural route", value: "INTRADURAL_ROUTE" },
    { label: "Intraepicardial route", value: "INTRAEPICARDIAL_ROUTE" },
    { label: "Intraepidermal", value: "INRAEPIDERMAL" },
    { label: "Intragastric route", value: "INTRAGASTRIC_ROUTE" },
    { label: "Intragingival route", value: "INTRAGINGIVAL_ROUTE" },
    { label: "Intraglandular", value: "INTRAGLANDULAR" },
    { label: "Intestinal", value: "INTESTINAL" },
    { label: "Intraabdominal route", value: "INTRAABDOMINAL_ROUTE" },
    { label: "Intraamniotic", value: "INTRAAMNIOTIC" },
    { label: "Intraarterial", value: "INTRAARTERIAL" },
    { label: "Intraarticular", value: "INTRAARTICULAR" },
    { label: "Intrabiliary route", value: "INTRABILIARY_ROUTE" },
    { label: "Intrabronchial route", value: "INTRABRONCHIAL_ROUTE" },
    { label: "Intrabursal", value: "INTRABUSAL" },
    { label: "Intracameral", value: "INTRACAMERAL" },
    { label: "Intracardiac", value: "INTRACARDIAC" },
    { label: "Intracartilaginous route", value: "INTRACARTILAGINOUS_ROUTE" },
    { label: "Intracavernous", value: "INTRACAVERNOUS" },
    { label: "Intracerebral route", value: "INTRACEREBRAL_ROUTE" },
    { label: "Intracerebroventricular", value: "INTRACEREBROVENTICULAR" },
    { label: "Intracervical", value: "INTRACERVICAL" },
    { label: "Intracholangiopancreatic", value: "INTRACOLANGIOPANCREATIC" },
    { label: "Intracisternal route", value: "INTRACISTERNAL_ROUTE" },
    { label: "Intrahepatic route", value: "INTRAHEPATIC_ROUTE" },
    { label: "Intraileal route", value: "INTRAILEAL_ROUTE" },
    { label: "Intrajejunal route", value: "INTRAJEJUNAL_ROUTE" },
    { label: "Intralesional", value: "INTRALESIONAL" },
    { label: "Intralingual route", value: "INTRALINGUAL_ROUTE" },
    { label: "Intraluminal route", value: "INTRALUMINAL_ROUTE" },
    { label: "Intralymphatic", value: "INTRALYMPHATIC" },
    { label: "Intramammary route", value: "INTRAMAMMARY_ROUTE" },
    { label: "Intramedullary route", value: "INTRAMEDULLARY_ROUTE" },
    { label: "Intrameningeal route", value: "INTRAMENINGEAL_ROUTE" },
    { label: "Intramural route", value: "INTRAMURAL_ROUTE" },
    { label: "Intramuscular", value: "INTRAMUSCULAR" },
    { label: "Intramyometrial route", value: "INTRAMYOMETRIAL_ROUTE" },
    { label: "Intraneural route", value: "INTRANEURAL_ROUTE" },
    { label: "Intraocular", value: "INTRAOcular" },
    { label: "Intraoesophageal route", value: "INTRAOESOPHAGEAL_ROUTE" },
    { label: "Intraosseous", value: "INTRAOSSOUS" },
   
    { label: "Intrapericardial route", value: "INTRAPERICARDIAL_ROUTE" },
    { label: "Intraperitoneal", value: "INTRAPERITONEAL" },
    { label: "Intrapleural", value: "INTRAPLEURAL" },
    { label: "Intraportal route", value: "INTRAPORTAL_ROUTE" },
    { label: "Intraprostatic route", value: "INTRAPROSTATIC_ROUTE" },
    { label: "Intrapulmonary route", value: "INTRAPULMONARY_ROUTE" },
    { label: "Intraputaminal", value: "INTRAPUTAMINAL" },
    { label: "Intrasinal route", value: "INTRASINAL_ROUTE" },
    { label: "Intraspinal route", value: "INTRASPINAL_ROUTE" },
    { label: "Intrasternal", value: "INTRASTERNAL" },
    { label: "Intrasynovial route", value: "INTRASYNOVIAL_ROUTE" },
    { label: "Intratendinous route", value: "INTRATENDINOUS_ROUTE" },
    { label: "Intratesticular route", value: "INTRATESTICULAR_ROUTE" },
    { label: "Intrathecal", value: "INTRATHECAL" },
    { label: "Intrathoracic route", value: "INTRATHORACIC_ROUTE" },
    { label: "Intratracheal route", value: "INTRATRACHEAL_ROUTE" },
    { label: "Intratumoral", value: "INTRATUMORAL" },
    { label: "Intratympanic route", value: "INTRATYMMPANIC_ROUTE" },
    { label: "Intrauterine", value: "INTRAUTERINE" },
    { label: "Intravascular route", value: "INTRAVASCULAR_ROUTE" },
    { label: "Intravenous", value: "INTRAVENOUS" },
    { label: "Intravenous central route", value: "INTRAVENOUS_CENTRAL_ROUTE" },
    { label: "Intravenous peripheral route", value: "INTRAVENOUS_PERIPHERAL_ROUTE" },
    { label: "Intraventricular cardiac", value: "INTRAVENTRICULAR_CARDIAC" },
    { label: "Intrasynovial route", value: "INTRASYNOVIAL_ROUTE" },
    { label: "Intratendinous route", value: "INTRATENDINOUS_ROUTE" },
    { label: "Intratesticular route", value: "INTRATESTICULAR_ROUTE" },
    { label: "Intrathecal", value: "INTRATHECAL" },
    { label: "Intrathoracic route", value: "INTRATHORACIC_ROUTE" },
    { label: "Intratracheal route", value: "INTRATRACHEAL_ROUTE" },
    { label: "Intratumoral", value: "INTRATUMORAL" },
    { label: "Intratympanic route", value: "INTRATYMMPANIC_ROUTE" },
    { label: "Intrauterine", value: "INTRAUTERINE" },
    { label: "Intravascular route", value: "INTRAVASCULAR_ROUTE" },
    { label: "Intravenous", value: "INTRAVENOUS" },
    { label: "Intraperitoneal", value: "INTRAPERITONEAL" },
    { label: "Intrapleural", value: "INTRAPLEURAL" },
    { label: "Intraportal route", value: "INTRAPORTAL_ROUTE" },
    { label: "Intraprostatic route", value: "INTRAPROSTATIC_ROUTE" },
    { label: "Intraputaminal", value: "INTRAPUTAMINAL" },
    { label: "Intrasinal route", value: "INTRASINAL_ROUTE" },
    { label: "Intraspinal route", value: "INTRASPINAL_ROUTE" },
    { label: "Intrasternal", value: "INTRASTERNAL" },
    { label: "Intrasynovial route", value: "INTRASYNOVIAL_ROUTE" },
    { label: "Intratendinous route", value: "INTRATENDINOUS_ROUTE" },
    { label: "Intratesticular route", value: "INTRATESTICULAR_ROUTE" },
    { label: "Intrathecal", value: "INTRATHECAL" },
    { label: "Intrathoracic route", value: "INTRATHORACIC_ROUTE" },
    { label: "Intratracheal route", value: "INTRATRACHEAL_ROUTE" },
    { label: "Intratumoral", value: "INTRATUMORAL" },
    { label: "Intratympanic route", value: "INTRATYMMPANIC_ROUTE" },
    { label: "Intrauterine", value: "INTRAUTERINE" },
    { label: "Intravascular route", value: "INTRAVASCULAR_ROUTE" },
    { label: "Intravenous", value: "INTRAVENOUS" },
    { label: "Intravenous central route", value: "INTRAVENOUS_CENTRAL_ROUTE" },
    { label: "Intravenous peripheral route", value: "INTRAVENOUS_PERIPHERAL_ROUTE" },
    { label: "Intraventricular cardiac", value: "INTRAVENTRICULAR_CARDIAC" },
    { label: "Intravesical", value: "INTRAVESICAL" },
    { label: "Intravitreal", value: "INTRAVITREAL" },
    { label: "Iontophoresis", value: "IONTOPHORESIS" },
    { label: "Jejunostomy route", value: "JEJUNOSTOMY_ROUTE" },
    { label: "Laryngeal route", value: "LARYNGEAL_ROUTE" },
    { label: "Line lock", value: "LINE LOCK" },
    { label: "Lower respiratory tract route", value: "LOWER_RESPIRATORY_TRACT_ROUTE" },
    { label: "Mucous fistula route", value: "MUCOSOUS_FISTULA_ROUTE" },
    { label: "Nasal", value: "NASAL" },
    { label: "Nasoduodenal route", value: "NASODUODENAL_ROUTE" },
    { label: "Nasogastric route", value: "NASOGASTRIC_ROUTE" },
    { label: "Nasojejunal route", value: "NASOJEJUNAL_ROUTE" },
    { label: "Ocular", value: "OCULAR" },
    { label: "Oesophagostomy route", value: "OESOPHAGOSTOMY_ROUTE" },
    { label: "Ophthalmic route", value: "OPHTHALMIC_ROUTE" },
    { label: "Oral", value: "ORAL" },
    { label: "Orogastric route", value: "OROGASTRIC_ROUTE" },
    { label: "Oromucosal", value: "OROMUCOSAL" },
    { label: "Oropharyngeal route", value: "OROPHARYNGEAL_ROUTE" },
    { label: "Paracervical route", value: "PARACERVICAL_ROUTE" },
    { label: "Paravertebral route", value: "PARAVERTEBRAL_ROUTE" },
    { label: "PEG tube route", value: "PEG_TUBE_ROUTE" },
    { label: "Percutaneous", value: "PERCUTANEOUS" },
    { label: "Percutaneous route", value: "PERCUTANEOUS_ROUTE" },
    { label: "Periarticular", value: "PERIARTICULAR" },
    { label: "Peribulbar", value: "PERIBULBAR" },
    { label: "Peribulbar ocular", value: "PERIBULBAR_OCULAR" },
    { label: "Periosseous", value: "PERIOSSEOUS" },
    { label: "Periosteal route", value: "PERIOSTEAL_ROUTE" },
    { label: "Peritendinous route", value: "PERITENDINOUS_ROUTE" },
    { label: "Peritumoral", value: "PERITUMORAL" },
    { label: "Periurethral route", value: "PERIURETHRAL_ROUTE" },
    { label: "Posterior juxtascleral route", value: "POSTERIOR_JUXTASSCLERAL_ROUTE" },
    { label: "Rectal", value: "RECTAL" },
    { label: "Regional perfusion", value: "REGIONAL_PERFUSION" },
    { label: "Respiratory tract route", value: "RESPIRATORY_TRACT_ROUTE" },
    { label: "Retrobulbar route", value: "RETROBULBAR_ROUTE" },
    { label: "Route of administration not applicable", value: "ROUTE_OF_ADMINISTRATION_NOT_APPLICABLE" },
    { label: "Subconjunctival", value: "SUBCONJUNCTIVAL" },
    { label: "Subcutaneous", value: "SUBCUTANEOUS" },
    { label: "Subgingival route", value: "SUBGINGIVAL_ROUTE" },
    { label: "Sublabial", value: "SUBLABIAL" },
    { label: "Sublesional route", value: "SUBLESIONAL_ROUTE" },
    { label: "Sublingual", value: "SUBLINGUAL" },
    { label: "Submucosal", value: "SUBMUCOSAL" },
    { label: "Submucosal rectal", value: "SUBMUCOSAL_RECTAL" },
    { label: "Suborbital route", value: "SUBORBITAL_ROUTE" },
    { label: "Subretinal", value: "SUBRETINAL" },
    { label: "Subtendinous route", value: "SUBTENDINOUS_ROUTE" },
    { label: "Suprachoroidal route", value: "SUPRACHOROIDAL_ROUTE" },
    { label: "Surgical cavity route", value: "SURGICAL_CAVITY_ROUTE" },
    { label: "Surgical drain route", value: "SURGICAL_DRAIN_ROUTE" },
    { label: "Topical route", value: "TOPICAL_ROUTE" },
    { label: "Transcervical route", value: "TRANSCERVICAL_ROUTE" },
    { label: "Transdermal", value: "TRANSDERMAL" },
    { label: "Transendocardial route", value: "TRANSENDOCARDIAL_ROUTE" },
    { label: "Translingual", value: "TRANSLINGUAL" },
    { label: "Transplacental route", value: "TRANSPLACENTAL_ROUTE" },
    { label: "Transtracheal route", value: "TRANSTRACHEAL_ROUTE" },
    { label: "Transtympanic route", value: "TRANSTYMPANIC_ROUTE" },
    { label: "Transurethral route", value: "TRANSURETHRAL_ROUTE" },
    { label: "Tumour cavity route", value: "TUMOUR_CAVITY_ROUTE" },
    { label: "Ureteral route", value: "URETERAL_ROUTE" },
    { label: "Urethral", value: "URETHRAL" },
    { label: "Urostomy route", value: "UROSTOMY_ROUTE" },
    { label: "Vaginal", value: "VAGINAL" },
  ];
  export const FREQUENCY_OPTIONS = [
    { label: "1 time a day", value: "1_TIME_A_DAY" },
    { label: "2 times a day", value: "2_TIMES_A_DAY" },
    { label: "3 times a day", value: "3_TIMES_A_DAY" },
  ];

  export const STATIC_ADDITIONAL_INFO_LIST = [
    {
      description: "White soft paraffin 13.2% / Liquid paraffin light 10.5% cream",
      doseForm: "Cream",
      manufacturer: "—",
      routes: ["Cutaneous", "Buccal", "Dental"],
      regulatory: [
        "HM Government — No Controlled Drug Status",
        "MHRA — Topical use only"
      ],
      externalInfo: "—"
    },
    {
      description: "White soft paraffin 30% / Liquid paraffin 40% ointment",
      doseForm: "Ointment",
      manufacturer: "MedCare Ltd.",
      routes: ["Cutaneous"],
      regulatory: [
        "UK Health Authority — External use",
        "MHRA — No Controlled Drug Status"
      ],
      externalInfo: "—"
    },
    {
      description: "White soft paraffin 14.5% / Liquid paraffin 12.6% cream",
      doseForm: "Cream",
      manufacturer: "—",
      routes: ["Cutaneous", "Colostomy route", "Dental"],
      regulatory: [
        "MHRA — Dermatological class",
        "NHS — Class A formulation"
      ],
      externalInfo: "—"
    },
    {
      description: "Liquid paraffin 11% cream",
      doseForm: "Cream",
      manufacturer: "SkinGuard Inc.",
      routes: ["Cutaneous", "Conjunctival route"],
      regulatory: [
        "MHRA — No Controlled Drug Status",
        "Approved for mucosal use"
      ],
      externalInfo: "—"
    },
    {
      description: "Liquid paraffin 20% / Urea 5% cream",
      doseForm: "Cream",
      manufacturer: "CareWell Pharmaceuticals",
      routes: ["Cutaneous", "Endocervical"],
      regulatory: [
        "UK Dermatology Authority",
        "Classified as dermatological"
      ],
      externalInfo: "carewellpharma.com/paraffin-urea"
    },
    {
      description: "White soft paraffin 40% paste",
      doseForm: "Paste",
      manufacturer: "Dermaceuticals Inc.",
      routes: ["Cutaneous", "Digestive tract route"],
      regulatory: [
        "MHRA — OTC Approval",
        "Dermatological use recommended"
      ],
      externalInfo: "—"
    },
    {
      description: "Liquid paraffin 25% / White soft paraffin 25% ointment",
      doseForm: "Ointment",
      manufacturer: "HealthPharma Ltd.",
      routes: ["Cutaneous", "Dental", "Colostomy route"],
      regulatory: [
        "MHRA — Oral & dermal approved",
        "Class B — Multi-route use"
      ],
      externalInfo: "healthpharma.com/paraffin-blend"
    },
    {
      description: "Liquid paraffin 12% cream",
      doseForm: "Cream",
      manufacturer: "Wellness Labs",
      routes: ["Cutaneous", "Caudal route"],
      regulatory: [
        "MHRA — No Controlled Drug Status",
        "For external perianal application"
      ],
      externalInfo: "—"
    },
    {
      description: "White soft paraffin 50% ointment",
      doseForm: "Ointment",
      manufacturer: "Generic Supplier",
      routes: ["Cutaneous", "Conjunctival route"],
      regulatory: [
        "Classified as OTC medicine",
        "MHRA — Mucosal safety tested"
      ],
      externalInfo: "mhra.gov.uk/soft-paraffin"
    },
    {
      description: "Liquid paraffin 10% lotion",
      doseForm: "Lotion",
      manufacturer: "CareLite Ltd.",
      routes: ["Cutaneous", "Digestive tract route"],
      regulatory: [
        "MHRA — Approved for skin and mucosa",
        "NHS — Pediatric safety listed"
      ],
      externalInfo: "carelite.com/products/paraffin-lotion"
    },
    // You can continue to replicate this pattern up to 15 objects as needed...
  ];
  

export const TIME_SLOT_MAPPING = {
    Morning: "08:00",
    Lunch: "13:00",
    Afternoon: "18:00",
    Evening: "21:00",
};
  