import { randomUUID } from "node:crypto";
import { z } from "zod";
import { fail, reply } from "../http.js";

const actorName = (u) => [u.firstName, u.lastName].filter(Boolean).join(" ") || u.email;
const caseSchema = z.object({
  clientId: z.uuid().nullable().optional(), kind: z.enum(["INCIDENT","SAFEGUARDING","COMPLAINT","AUDIT_FINDING"]),
  severity: z.enum(["LOW","MEDIUM","HIGH","CRITICAL"]), title: z.string().trim().min(3).max(160),
  description: z.string().trim().min(10).max(5000), ownerId: z.uuid().nullable().optional(), dueAt: z.iso.datetime().nullable().optional()
});

export function registerGovernance({ db, auth }, route) {
  const admin = (req) => auth.admin(req);
  const tenantUser = async (id, agency, requiredRole) => {
    if (!id) return null;
    const row = (await db.query("SELECT id,role FROM users WHERE id=$1 AND agency_id=$2 AND deleted_at IS NULL", [id, agency])).rows[0];
    if (!row || (requiredRole && row.role !== requiredRole)) fail(400, "Selected person is not eligible");
    return row;
  };
  route("GET", "/api/governance/overview", async (req,res) => {
    admin(req);
    const agency=req.user.agencyId;
    const [cases,policies,credentials,ai,lastRun]=await Promise.all([
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status<>'CLOSED')::int open,count(*) FILTER(WHERE due_at<CURRENT_TIMESTAMP AND status<>'CLOSED')::int overdue FROM node_quality_cases WHERE agency_id=$1`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='ACTIVE')::int active,count(*) FILTER(WHERE review_at<=CURRENT_DATE+30 AND status='ACTIVE')::int due FROM node_policy_register WHERE agency_id=$1`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE expires_at<CURRENT_DATE)::int expired,count(*) FILTER(WHERE expires_at BETWEEN CURRENT_DATE AND CURRENT_DATE+30)::int expiring FROM node_staff_credentials WHERE agency_id=$1 AND status='VALID'`,[agency]),
      db.query(`SELECT count(*)::int total,count(*) FILTER(WHERE status='PENDING')::int pending FROM node_ai_reviews WHERE agency_id=$1`,[agency]),
      db.query(`SELECT id,status,findings,created_at AS "createdAt" FROM node_data_quality_runs WHERE agency_id=$1 ORDER BY created_at DESC LIMIT 1`,[agency])
    ]);
    return reply(res,{quality:cases.rows[0],policies:policies.rows[0],credentials:credentials.rows[0],ai:ai.rows[0],lastDataQualityRun:lastRun.rows[0]||null});
  });
  route("GET", "/api/governance/cases", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT q.*,u.first_name||' '||u.last_name AS "ownerName" FROM node_quality_cases q LEFT JOIN users u ON u.id=q.owner_id WHERE q.agency_id=$1 ORDER BY q.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/cases", async(req,res)=>{admin(req);const p=caseSchema.safeParse(req.body);if(!p.success)fail(400,p.error.issues[0]?.message||"Invalid case");const b=p.data;await tenantUser(b.clientId,req.user.agencyId,"USER");const owner=await tenantUser(b.ownerId,req.user.agencyId);if(owner?.role==='USER')fail(400,"Case owner must be a staff member");const id=randomUUID();await db.query(`INSERT INTO node_quality_cases(id,agency_id,client_id,kind,severity,title,description,owner_id,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)`,[id,req.user.agencyId,b.clientId||null,b.kind,b.severity,b.title,b.description,b.ownerId||null,b.dueAt||null,req.user.id]);return reply(res,{id},"Quality case recorded",201)});
  route("POST", "/api/governance/cases/:id/status", async(req,res)=>{admin(req);const p=z.object({status:z.enum(["OPEN","INVESTIGATING","ACTION_REQUIRED","CLOSED"]),reason:z.string().trim().min(5).max(1000),revision:z.number().int().positive()}).safeParse(req.body);if(!p.success)fail(400,"Enter a status, reason and current revision");const changed=await db.query(`UPDATE node_quality_cases SET status=$3,revision=revision+1,updated_at=CURRENT_TIMESTAMP,closed_at=CASE WHEN $3='CLOSED' THEN CURRENT_TIMESTAMP ELSE NULL END,closed_by=CASE WHEN $3='CLOSED' THEN $4::uuid ELSE NULL END,description=description||E'\n\nDecision: '||$5 WHERE id=$1 AND agency_id=$2 AND revision=$6 RETURNING id,revision`,[req.params.id,req.user.agencyId,p.data.status,req.user.id,p.data.reason,p.data.revision]);if(!changed.rows.length)fail(409,"Case changed or was not found");return reply(res,changed.rows[0],"Case status updated")});
  route("POST", "/api/governance/cases/:id/actions", async(req,res)=>{admin(req);const p=z.object({title:z.string().trim().min(3).max(300),ownerId:z.uuid().nullable().optional(),dueAt:z.iso.datetime().nullable().optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter a valid corrective action");const q=(await db.query("SELECT id FROM node_quality_cases WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!q)fail(404,"Quality case not found");const owner=await tenantUser(p.data.ownerId,req.user.agencyId);if(owner?.role==='USER')fail(400,"Action owner must be a staff member");const id=randomUUID();await db.query("INSERT INTO node_quality_actions(id,case_id,title,owner_id,due_at,created_by) VALUES($1,$2,$3,$4,$5,$6)",[id,q.id,p.data.title,p.data.ownerId||null,p.data.dueAt||null,req.user.id]);return reply(res,{id},"Corrective action added",201)});
  route("GET", "/api/governance/policies", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT p.*,count(a.user_id)::int AS acknowledgements FROM node_policy_register p LEFT JOIN node_policy_acknowledgements a ON a.policy_id=p.id WHERE p.agency_id=$1 GROUP BY p.id ORDER BY p.updated_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/policies", async(req,res)=>{admin(req);const p=z.object({title:z.string().trim().min(3).max(160),version:z.string().trim().min(1).max(30),status:z.enum(["DRAFT","ACTIVE","RETIRED"]),effectiveAt:z.string().nullable().optional(),reviewAt:z.string().nullable().optional(),documentUrl:z.union([z.url(),z.literal(""),z.null()]).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid policy details");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_policy_register(id,agency_id,title,version,status,effective_at,review_at,document_url,approved_by,approved_at,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$9)`,[id,req.user.agencyId,b.title,b.version,b.status,b.effectiveAt||null,b.reviewAt||null,b.documentUrl||null,req.user.id,b.status==='ACTIVE'?new Date():null]);return reply(res,{id},"Policy recorded",201)});
  route("POST", "/api/governance/policies/:id/acknowledge", async(req,res)=>{const policy=(await db.query("SELECT id FROM node_policy_register WHERE id=$1 AND agency_id=$2 AND status='ACTIVE'",[req.params.id,req.user.agencyId])).rows[0];if(!policy)fail(404,"Active policy not found");await db.query("INSERT INTO node_policy_acknowledgements(policy_id,user_id) VALUES($1,$2) ON CONFLICT DO NOTHING",[policy.id,req.user.id]);return reply(res,{},"Policy acknowledged")});
  route("GET", "/api/governance/credentials", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT c.*,u.first_name||' '||u.last_name AS "staffName",CASE WHEN c.expires_at<CURRENT_DATE THEN 'EXPIRED' WHEN c.expires_at<=CURRENT_DATE+30 THEN 'EXPIRING' ELSE c.status END AS "displayStatus" FROM node_staff_credentials c JOIN users u ON u.id=c.staff_id WHERE c.agency_id=$1 ORDER BY c.expires_at NULLS LAST`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/credentials", async(req,res)=>{admin(req);const p=z.object({staffId:z.uuid(),kind:z.string().trim().min(2).max(100),reference:z.string().trim().max(100).optional(),issuedAt:z.string().nullable().optional(),expiresAt:z.string().nullable().optional(),evidenceUrl:z.union([z.url(),z.literal(""),z.null()]).optional()}).safeParse(req.body);if(!p.success)fail(400,"Enter valid credential details");const staff=await tenantUser(p.data.staffId,req.user.agencyId);if(staff.role==='USER')fail(400,"Credential holder must be a staff member");const id=randomUUID(),b=p.data;await db.query(`INSERT INTO node_staff_credentials(id,agency_id,staff_id,kind,reference,issued_at,expires_at,evidence_url,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)`,[id,req.user.agencyId,b.staffId,b.kind,b.reference||null,b.issuedAt||null,b.expiresAt||null,b.evidenceUrl||null,req.user.id]);return reply(res,{id},"Credential recorded",201)});
  route("GET", "/api/governance/ai-reviews", async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT a.*,u.first_name||' '||u.last_name AS "clientName" FROM node_ai_reviews a JOIN users u ON u.id=a.client_id WHERE a.agency_id=$1 ORDER BY a.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/ai-reviews/generate", async(req,res)=>{admin(req);const p=z.object({clientId:z.uuid(),kind:z.enum(["NOTE_SUMMARY","RISK_SIGNAL"])}).safeParse(req.body);if(!p.success)fail(400,"Choose a client and review type");await tenantUser(p.data.clientId,req.user.agencyId,"USER");const rows=(await db.query(`SELECT id,kind,title,body,created_at AS "createdAt" FROM node_client_entries WHERE agency_id=$1 AND client_id=$2 AND kind IN ('NOTE','OBSERVATION','INCIDENT','CONCERN') ORDER BY created_at DESC LIMIT 20`,[req.user.agencyId,p.data.clientId])).rows;if(!rows.length)fail(409,"There are no eligible notes to review");const flagged=rows.filter(x=>/fall|missed|pain|injur|medication|wound|concern/i.test(`${x.title} ${x.body}`));const suggestion=p.data.kind==='NOTE_SUMMARY'?`Review summary: ${rows.length} recent care entries were found. ${flagged.length} contain terms that may need attention.`:`${flagged.length} of ${rows.length} recent entries contain possible attention terms. A qualified person must inspect the cited records.`;const id=randomUUID();await db.query(`INSERT INTO node_ai_reviews(id,agency_id,client_id,kind,suggestion,evidence,model_info,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)`,[id,req.user.agencyId,p.data.clientId,p.data.kind,suggestion,JSON.stringify((flagged.length?flagged:rows.slice(0,5)).map(x=>({entryId:x.id,kind:x.kind,title:x.title,createdAt:x.createdAt}))),JSON.stringify({type:'rules-assisted',version:'gate-d-1',limitations:'Keyword signals are not clinical conclusions'}),req.user.id]);return reply(res,{id,suggestion},"Suggestion queued for human review",201)});
  route("POST", "/api/governance/ai-reviews/:id/decision", async(req,res)=>{admin(req);const p=z.object({decision:z.enum(["APPROVED","REJECTED"]),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Record an approval or rejection with a reason");const changed=await db.query(`UPDATE node_ai_reviews SET status=$3,reviewed_by=$4,decision_reason=$5,reviewed_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 AND status='PENDING' RETURNING id,status`,[req.params.id,req.user.agencyId,p.data.decision,req.user.id,p.data.reason]);if(!changed.rows.length)fail(409,"Review was already decided or not found");return reply(res,changed.rows[0],"Human review recorded; no care record was changed")});
  route("GET", "/api/governance/metrics", async(req,res)=>{admin(req);await seedMetrics(db,req.user);return reply(res,(await db.query(`SELECT metric_key AS "metricKey",label,definition,owner,active,updated_at AS "updatedAt" FROM node_metric_definitions WHERE agency_id=$1 ORDER BY metric_key`,[req.user.agencyId])).rows)});
  route("POST", "/api/governance/data-quality/run", async(req,res)=>{admin(req);const agency=req.user.agencyId;const findings=(await Promise.all([
    db.query(`SELECT count(*)::int n FROM node_roster_visits WHERE agency_id=$1 AND status='COMPLETED' AND (actual_start IS NULL OR actual_end IS NULL)`,[agency]),
    db.query(`SELECT count(*)::int n FROM node_quality_cases WHERE agency_id=$1 AND status<>'CLOSED' AND due_at<CURRENT_TIMESTAMP`,[agency]),
    db.query(`SELECT count(*)::int n FROM node_staff_credentials WHERE agency_id=$1 AND status='VALID' AND expires_at<CURRENT_DATE`,[agency])
  ])).map((r,i)=>({key:['completed_visits_missing_actuals','overdue_quality_cases','expired_staff_credentials'][i],count:r.rows[0].n,status:r.rows[0].n?'FAIL':'PASS'}));const id=randomUUID(),status=findings.some(x=>x.status==='FAIL')?'ATTENTION':'PASS';await db.query("INSERT INTO node_data_quality_runs(id,agency_id,status,findings,created_by) VALUES($1,$2,$3,$4,$5)",[id,agency,status,JSON.stringify(findings),req.user.id]);return reply(res,{id,status,findings,asOf:new Date().toISOString()},"Data-quality checks completed")});
  route("GET", "/api/governance/evidence-pack", async(req,res)=>{admin(req);const agency=req.user.agencyId;const [overview,caseRows,policies,credentials,reviews,checks]=await Promise.all([db.query(`SELECT count(*)::int AS "qualityCases" FROM node_quality_cases WHERE agency_id=$1`,[agency]),db.query(`SELECT kind,severity,status,count(*)::int count FROM node_quality_cases WHERE agency_id=$1 GROUP BY kind,severity,status`,[agency]),db.query(`SELECT title,version,status,effective_at AS "effectiveAt",review_at AS "reviewAt" FROM node_policy_register WHERE agency_id=$1 ORDER BY title`,[agency]),db.query(`SELECT kind,status,expires_at AS "expiresAt" FROM node_staff_credentials WHERE agency_id=$1 ORDER BY expires_at`,[agency]),db.query(`SELECT kind,status,count(*)::int count FROM node_ai_reviews WHERE agency_id=$1 GROUP BY kind,status`,[agency]),db.query(`SELECT status,findings,created_at AS "createdAt" FROM node_data_quality_runs WHERE agency_id=$1 ORDER BY created_at DESC LIMIT 10`,[agency])]);return reply(res,{generatedAt:new Date().toISOString(),generatedBy:actorName(req.user),agencyId:agency,summary:overview.rows[0],cases:caseRows.rows,policies:policies.rows,credentials:credentials.rows,aiReviews:reviews.rows,dataQualityRuns:checks.rows,statement:'AI suggestions require human approval and do not modify clinical records.'})});
}

async function seedMetrics(db,user){
  for(const m of [
    ['visit_completion_rate','Visit completion rate','Completed visits divided by all non-cancelled visits in the selected period.','Registered manager'],
    ['actual_hours_delivered','Actual hours delivered','Elapsed time between verified check-in and check-out for completed visits with both timestamps.','Operations lead'],
    ['open_quality_cases','Open quality cases','Quality cases whose status is not Closed.','Quality lead'],
    ['credential_compliance','Credential compliance','Active staff credentials that have not passed their expiry date.','People lead']
  ]) await db.query(`INSERT INTO node_metric_definitions(agency_id,metric_key,label,definition,owner,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`,[user.agencyId,...m,user.id]);
}
