import { randomUUID } from "node:crypto";
import { z } from "zod";
import { fail, reply } from "../http.js";
import { decryptSecret, encryptSecret, newMfaSecret, verifyTotp } from "../mfa.js";

export function registerSecurity({db,auth,config},route){
  route("GET","/api/security/sessions",async(req,res)=>reply(res,(await db.query(`SELECT id,device_name AS "deviceName",ip_address AS "ipAddress",user_agent AS "userAgent",created_at AS "createdAt",last_seen_at AS "lastSeenAt",expires_at AS "expiresAt",mfa_verified_at AS "mfaVerifiedAt",id=$2 AS current FROM node_sessions WHERE user_id=$1 AND revoked_at IS NULL AND expires_at>CURRENT_TIMESTAMP ORDER BY last_seen_at DESC`,[req.user.id,req.sessionId])).rows));
  route("DELETE","/api/security/sessions/:id",async(req,res)=>{const changed=await db.query("UPDATE node_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE id=$1 AND user_id=$2 AND revoked_at IS NULL RETURNING id",[req.params.id,req.user.id]);if(!changed.rows.length)fail(404,"Session not found");return reply(res,{},"Device session revoked")});
  route("POST","/api/security/sessions/revoke-others",async(req,res)=>{await auth.requireRecent(req);await db.query("UPDATE node_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=$1 AND id<>$2 AND revoked_at IS NULL",[req.user.id,req.sessionId]);return reply(res,{},"Other device sessions revoked")});
  route("GET","/api/security/mfa",async(req,res)=>{const row=(await db.query("SELECT enabled,enabled_at AS \"enabledAt\" FROM node_mfa_settings WHERE user_id=$1",[req.user.id])).rows[0];return reply(res,row||{enabled:false,enabledAt:null})});
  route("POST","/api/security/mfa/setup",async(req,res)=>{const secret=newMfaSecret(),cipher=encryptSecret(secret,config.mfaEncryptionKey||config.jwtSecret);await db.query(`INSERT INTO node_mfa_settings(user_id,secret_cipher,enabled) VALUES($1,$2,false) ON CONFLICT(user_id) DO UPDATE SET secret_cipher=EXCLUDED.secret_cipher,enabled=false,enabled_at=NULL,updated_at=CURRENT_TIMESTAMP`,[req.user.id,cipher]);const label=encodeURIComponent(`Caremonitor:${req.user.email}`),issuer=encodeURIComponent("Caremonitor by AniProTech");return reply(res,{secret,otpauthUrl:`otpauth://totp/${label}?secret=${secret}&issuer=${issuer}&algorithm=SHA1&digits=6&period=30`},"Authenticator setup started")});
  route("POST","/api/security/mfa/enable",async(req,res)=>{const code=z.string().regex(/^\d{6}$/).safeParse(req.body.code);if(!code.success)fail(400,"Enter the six-digit authentication code");const row=(await db.query("SELECT secret_cipher FROM node_mfa_settings WHERE user_id=$1",[req.user.id])).rows[0];if(!row||!verifyTotp(decryptSecret(row.secret_cipher,config.mfaEncryptionKey||config.jwtSecret),code.data))fail(400,"Authentication code is incorrect");await db.query("UPDATE node_mfa_settings SET enabled=true,enabled_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE user_id=$1",[req.user.id]);await db.query("UPDATE node_sessions SET mfa_verified_at=CURRENT_TIMESTAMP WHERE id=$1",[req.sessionId]);return reply(res,{},"Multi-factor authentication enabled")});
  route("POST","/api/security/reauth",async(req,res)=>{const row=(await db.query("SELECT secret_cipher,enabled FROM node_mfa_settings WHERE user_id=$1",[req.user.id])).rows[0];if(!row?.enabled)fail(400,"Enable MFA before using authentication codes");if(!verifyTotp(decryptSecret(row.secret_cipher,config.mfaEncryptionKey||config.jwtSecret),req.body.code))fail(401,"Authentication code is incorrect");await db.query("UPDATE node_sessions SET mfa_verified_at=CURRENT_TIMESTAMP WHERE id=$1",[req.sessionId]);return reply(res,{validForMinutes:10},"Identity confirmed")});
  route("DELETE","/api/security/mfa",async(req,res)=>{await auth.requireRecent(req);await db.query("DELETE FROM node_mfa_settings WHERE user_id=$1",[req.user.id]);return reply(res,{},"Multi-factor authentication disabled")});
}

export function registerPrivacy({db,auth},route){
  const admin=(req)=>auth.admin(req);
  route("GET","/api/privacy/subjects",async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT id,first_name||' '||last_name AS name,email,role FROM users WHERE agency_id=$1 ORDER BY first_name,last_name`,[req.user.agencyId])).rows)});
  route("GET","/api/privacy/retention",async(req,res)=>{admin(req);const row=(await db.query(`SELECT care_records_days AS "careRecordsDays",audit_days AS "auditDays",finance_days AS "financeDays",inactive_accounts_days AS "inactiveAccountsDays",updated_at AS "updatedAt" FROM node_retention_policies WHERE agency_id=$1`,[req.user.agencyId])).rows[0];return reply(res,row||{careRecordsDays:2922,auditDays:2557,financeDays:2557,inactiveAccountsDays:2557})});
  route("PUT","/api/privacy/retention",async(req,res)=>{admin(req);await auth.requireRecent(req);const p=z.object({careRecordsDays:z.number().int().min(365).max(10000),auditDays:z.number().int().min(365).max(10000),financeDays:z.number().int().min(365).max(10000),inactiveAccountsDays:z.number().int().min(365).max(10000)}).safeParse(req.body);if(!p.success)fail(400,"Enter valid retention periods");const b=p.data;await db.query(`INSERT INTO node_retention_policies(agency_id,care_records_days,audit_days,finance_days,inactive_accounts_days,updated_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(agency_id) DO UPDATE SET care_records_days=EXCLUDED.care_records_days,audit_days=EXCLUDED.audit_days,finance_days=EXCLUDED.finance_days,inactive_accounts_days=EXCLUDED.inactive_accounts_days,updated_by=EXCLUDED.updated_by,updated_at=CURRENT_TIMESTAMP`,[req.user.agencyId,b.careRecordsDays,b.auditDays,b.financeDays,b.inactiveAccountsDays,req.user.id]);return reply(res,b,"Retention policy saved")});
  route("GET","/api/privacy/requests",async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT p.id,p.kind,p.status,p.reason,p.decision_reason AS "decisionReason",p.created_at AS "createdAt",u.first_name||' '||u.last_name AS "subjectName" FROM node_privacy_requests p JOIN users u ON u.id=p.subject_user_id WHERE p.agency_id=$1 ORDER BY p.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST","/api/privacy/requests",async(req,res)=>{admin(req);const p=z.object({subjectUserId:z.uuid(),kind:z.enum(["EXPORT","CORRECTION","ERASURE"]),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Enter a subject, request type and reason");const user=(await db.query("SELECT id FROM users WHERE id=$1 AND agency_id=$2",[p.data.subjectUserId,req.user.agencyId])).rows[0];if(!user)fail(404,"Data subject not found");const id=randomUUID();await db.query("INSERT INTO node_privacy_requests(id,agency_id,subject_user_id,kind,reason,requested_by) VALUES($1,$2,$3,$4,$5,$6)",[id,req.user.agencyId,user.id,p.data.kind,p.data.reason,req.user.id]);return reply(res,{id},"Privacy request recorded",201)});
  route("POST","/api/privacy/requests/:id/status",async(req,res)=>{admin(req);await auth.requireRecent(req);const p=z.object({status:z.enum(["IN_REVIEW","APPROVED","REJECTED","COMPLETED"]),decisionReason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Enter a decision and reason");const old=(await db.query("SELECT * FROM node_privacy_requests WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!old)fail(404,"Privacy request not found");if(old.kind==="ERASURE"&&["APPROVED","COMPLETED"].includes(p.data.status)&&(await db.query("SELECT 1 FROM node_legal_holds WHERE agency_id=$1 AND subject_user_id=$2 AND active=true",[req.user.agencyId,old.subject_user_id])).rows[0])fail(409,"This person is under an active legal hold");await db.query("UPDATE node_privacy_requests SET status=$2,decision_reason=$3,decided_by=$4,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[old.id,p.data.status,p.data.decisionReason,req.user.id]);return reply(res,{},"Privacy request updated")});
  route("POST","/api/privacy/requests/:id/execute",async(req,res)=>{admin(req);await auth.requireRecent(req);const item=(await db.query("SELECT * FROM node_privacy_requests WHERE id=$1 AND agency_id=$2",[req.params.id,req.user.agencyId])).rows[0];if(!item||item.status!=="APPROVED")fail(409,"Approve this privacy request before execution");if(item.kind==="CORRECTION")fail(400,"Apply the approved correction in the relevant record and then mark the request completed");if((await db.query("SELECT 1 FROM node_legal_holds WHERE agency_id=$1 AND subject_user_id=$2 AND active=true",[req.user.agencyId,item.subject_user_id])).rows[0])fail(409,"This person is under an active legal hold");if(item.kind==="EXPORT"){const user=(await db.query("SELECT id,first_name,last_name,middle_name,email,primary_phone,secondary_phone,role,is_active,created_at,updated_at FROM users WHERE id=$1 AND agency_id=$2",[item.subject_user_id,req.user.agencyId])).rows[0],addresses=(await db.query("SELECT * FROM user_primary_address WHERE user_id=$1",[item.subject_user_id])).rows,visits=(await db.query(`SELECT id,visit_date::text date,start_time::text AS "startTime",end_time::text AS "endTime",actual_start AS "actualStart",actual_end AS "actualEnd",title,status FROM node_roster_visits WHERE agency_id=$2 AND (client_id=$1 OR staff_id=$1) ORDER BY visit_date`,[item.subject_user_id,req.user.agencyId])).rows;await db.query("UPDATE node_privacy_requests SET status='COMPLETED',decided_by=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[item.id,req.user.id]);return reply(res,{generatedAt:new Date().toISOString(),subject:user,addresses,visits},"Privacy export generated");}await db.transaction(async()=>{await db.query("UPDATE users SET first_name='Erased',last_name='User',middle_name=NULL,email=$2,primary_phone=NULL,secondary_phone=NULL,is_active=false,updated_by=$3,updated_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$4",[item.subject_user_id,`erased-${item.subject_user_id}@invalid.local`,req.user.id,req.user.agencyId]);await db.query("UPDATE user_primary_address SET address_line1='Erased',address_line2=NULL,city='Erased',postal_code='ERASED',latitude=NULL,longitude=NULL WHERE user_id=$1",[item.subject_user_id]);await db.query("UPDATE node_sessions SET revoked_at=CURRENT_TIMESTAMP WHERE user_id=$1",[item.subject_user_id]);await db.query("DELETE FROM node_mfa_settings WHERE user_id=$1",[item.subject_user_id]);await db.query("UPDATE node_privacy_requests SET status='COMPLETED',decided_by=$2,updated_at=CURRENT_TIMESTAMP WHERE id=$1",[item.id,req.user.id]);});return reply(res,{},"Personal identifiers erased; required care, audit and financial records were retained")});
  route("POST","/api/privacy/legal-holds",async(req,res)=>{admin(req);await auth.requireRecent(req);const p=z.object({subjectUserId:z.uuid(),reason:z.string().trim().min(10).max(2000)}).safeParse(req.body);if(!p.success)fail(400,"Enter a subject and legal-hold reason");const id=randomUUID();await db.query("INSERT INTO node_legal_holds(id,agency_id,subject_user_id,reason,created_by) SELECT $1,$2,id,$3,$4 FROM users WHERE id=$5 AND agency_id=$2",[id,req.user.agencyId,p.data.reason,req.user.id,p.data.subjectUserId]);return reply(res,{id},"Legal hold created",201)});
  route("GET","/api/privacy/legal-holds",async(req,res)=>{admin(req);return reply(res,(await db.query(`SELECT h.id,h.subject_user_id AS "subjectUserId",h.reason,h.active,h.created_at AS "createdAt",u.first_name||' '||u.last_name AS "subjectName" FROM node_legal_holds h JOIN users u ON u.id=h.subject_user_id WHERE h.agency_id=$1 ORDER BY h.created_at DESC`,[req.user.agencyId])).rows)});
  route("POST","/api/privacy/legal-holds/:id/release",async(req,res)=>{admin(req);await auth.requireRecent(req);const changed=await db.query("UPDATE node_legal_holds SET active=false,released_by=$3,released_at=CURRENT_TIMESTAMP WHERE id=$1 AND agency_id=$2 AND active=true RETURNING id",[req.params.id,req.user.agencyId,req.user.id]);if(!changed.rows.length)fail(404,"Active legal hold not found");return reply(res,{},"Legal hold released")});
}
