import { useEffect, useState } from "react";
import { _get, _post, _put } from "../../utils/ApiService";
import { showError, showSuccess } from "../../utils/toaster";

export default function PrivacyPanel(){
 const defaults={careRecordsDays:2922,auditDays:2557,financeDays:2557,inactiveAccountsDays:2557};
 const [policy,setPolicy]=useState(defaults),[subjects,setSubjects]=useState([]),[requests,setRequests]=useState([]),[holds,setHolds]=useState([]),[form,setForm]=useState({subjectUserId:"",kind:"EXPORT",reason:""}),[hold,setHold]=useState({subjectUserId:"",reason:""}),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [p,s,r,h]=await Promise.all([_get("/api/privacy/retention"),_get("/api/privacy/subjects"),_get("/api/privacy/requests"),_get("/api/privacy/legal-holds")]);setPolicy(p.data.results.data);setSubjects(s.data.results.data);setRequests(r.data.results.data);setHolds(h.data.results.data)}catch(e){showError(e.response?.data?.message||"Unable to load privacy controls")}};
 useEffect(()=>{load()},[]);
 const run=async(work,message)=>{setBusy(true);try{return await work().then(async value=>{showSuccess(message);await load();return value})}catch(e){showError(e.response?.data?.message||"Privacy action failed")}finally{setBusy(false)}};
 const download=(value,name)=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));a.download=name;a.click();URL.revokeObjectURL(a.href)};
 return <div><h2 className="text-xl font-semibold">Privacy and retention</h2><p className="mt-1 text-sm text-slate-500">Control retention, data-subject requests and legal holds. Sensitive actions require a recent sign-in or MFA confirmation.</p>
  <section className="mt-6 rounded-xl border p-5"><h3 className="font-semibold">Retention policy</h3><div className="mt-3 grid gap-3 md:grid-cols-2">{[["careRecordsDays","Care records"],["auditDays","Audit records"],["financeDays","Finance records"],["inactiveAccountsDays","Inactive accounts"]].map(([key,label])=><label key={key} className="text-sm">{label} (days)<input type="number" min="365" max="10000" value={policy[key]} onChange={e=>setPolicy({...policy,[key]:Number(e.target.value)})} className="mt-1 w-full rounded border px-3 py-2"/></label>)}</div><button type="button" disabled={busy} onClick={()=>run(()=>_put("/api/privacy/retention",policy),"Retention policy saved")} className="mt-4 rounded bg-customTextNavy px-4 py-2 text-white">Save retention policy</button></section>
  <section className="mt-6 rounded-xl border p-5"><h3 className="font-semibold">Record a privacy request</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><select value={form.subjectUserId} onChange={e=>setForm({...form,subjectUserId:e.target.value})} className="rounded border px-3 py-2"><option value="">Choose person</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name} · {s.role}</option>)}</select><select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})} className="rounded border px-3 py-2"><option value="EXPORT">Access/export</option><option value="CORRECTION">Correction</option><option value="ERASURE">Erasure</option></select><textarea value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="Request and identity-verification details" className="rounded border px-3 py-2 md:col-span-2"/></div><button type="button" disabled={busy||!form.subjectUserId||form.reason.length<10} onClick={()=>run(()=>_post("/api/privacy/requests",form),"Privacy request recorded")} className="mt-3 rounded bg-customTextNavy px-4 py-2 text-white disabled:opacity-50">Record request</button></section>
  <section className="mt-6"><h3 className="font-semibold">Requests</h3><div className="mt-3 space-y-2">{requests.map(r=><div key={r.id} className="rounded border p-4"><div className="flex flex-wrap items-center justify-between gap-2"><div><strong>{r.kind} · {r.subjectName}</strong><p className="text-sm text-slate-500">{r.status} · {r.reason}</p></div><div className="flex gap-2">{r.status==="OPEN"&&<button type="button" onClick={()=>run(()=>_post(`/api/privacy/requests/${r.id}/status`,{status:"APPROVED",decisionReason:"Identity and request verified by the authorised privacy administrator"}),"Request approved")} className="rounded border px-3 py-1">Approve</button>}{r.status==="APPROVED"&&r.kind!=="CORRECTION"&&<button type="button" onClick={async()=>{const response=await run(()=>_post(`/api/privacy/requests/${r.id}/execute`,{}),"Request completed");if(response&&r.kind==="EXPORT")download(response.data.results.data,`privacy-export-${r.id}.json`)}} className="rounded border px-3 py-1">Execute</button>}</div></div></div>)}</div></section>
  <section className="mt-6"><h3 className="font-semibold">Legal holds</h3><div className="mt-3 grid gap-3 md:grid-cols-[1fr_2fr_auto]"><select value={hold.subjectUserId} onChange={e=>setHold({...hold,subjectUserId:e.target.value})} className="rounded border px-3 py-2"><option value="">Choose person</option>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><input value={hold.reason} onChange={e=>setHold({...hold,reason:e.target.value})} placeholder="Legal-hold reason" className="rounded border px-3 py-2"/><button type="button" disabled={busy||!hold.subjectUserId||hold.reason.length<10} onClick={()=>run(()=>_post("/api/privacy/legal-holds",hold),"Legal hold created")} className="rounded border px-3 py-2 disabled:opacity-50">Create hold</button></div><div className="mt-3 space-y-2">{holds.filter(h=>h.active).map(h=><div key={h.id} className="flex items-center justify-between rounded border p-4"><div><strong>{h.subjectName}</strong><p className="text-sm text-slate-500">{h.reason}</p></div><button type="button" onClick={()=>run(()=>_post(`/api/privacy/legal-holds/${h.id}/release`,{}),"Legal hold released")} className="text-sm text-red-700">Release</button></div>)}{!holds.some(h=>h.active)&&<p className="text-sm text-slate-500">No active legal holds.</p>}</div></section>
 </div>;
}
