import { useEffect, useState } from "react";
import { QRCodeSVG } from "qrcode.react";
import { _delete, _get, _post } from "../../utils/ApiService";
import { showError, showSuccess } from "../../utils/toaster";

export default function SecurityPanel(){
 const [mfa,setMfa]=useState({enabled:false}),[setup,setSetup]=useState(null),[code,setCode]=useState(""),[sessions,setSessions]=useState([]),[busy,setBusy]=useState(false);
 const load=async()=>{try{const [m,s]=await Promise.all([_get("/api/security/mfa"),_get("/api/security/sessions")]);setMfa(m.data.results.data);setSessions(s.data.results.data)}catch(e){showError(e.response?.data?.message||"Unable to load security settings")}};
 useEffect(()=>{load()},[]);
 const run=async(work,message)=>{setBusy(true);try{await work();showSuccess(message);setCode("");setSetup(null);await load()}catch(e){showError(e.response?.data?.message||"Security update failed")}finally{setBusy(false)}};
 return <div><h2 className="text-xl font-semibold">Security and devices</h2><p className="mt-1 text-sm text-slate-500">Protect administrator access and review signed-in devices.</p>
  <section className="mt-6 rounded-xl border p-5"><div className="flex items-center justify-between"><div><h3 className="font-semibold">Authenticator app</h3><p className="text-sm text-slate-500">{mfa.enabled?"Enabled. A code is required after every magic-link sign-in.":"Add a second factor to your one-time email link."}</p></div><span className={`rounded-full px-3 py-1 text-sm ${mfa.enabled?"bg-emerald-100 text-emerald-800":"bg-amber-100 text-amber-800"}`}>{mfa.enabled?"Enabled":"Not enabled"}</span></div>
   {mfa.enabled&&<div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} maxLength="6" inputMode="numeric" className="rounded-lg border px-3 py-2" placeholder="Current six-digit code"/><button type="button" disabled={busy||code.length!==6} onClick={()=>run(()=>_post("/api/security/reauth",{code}),"Identity confirmed for sensitive changes")} className="rounded border px-3 py-2 disabled:opacity-50">Confirm identity</button></div>}
   {!mfa.enabled&&!setup&&<button type="button" disabled={busy} onClick={async()=>{setBusy(true);try{setSetup((await _post("/api/security/mfa/setup",{})).data.results.data)}catch(e){showError(e.response?.data?.message||"Unable to start authenticator setup")}finally{setBusy(false)}}} className="mt-4 rounded-lg bg-customTextNavy px-4 py-2 text-white">Set up authenticator</button>}
   {setup&&<div className="mt-5 grid gap-5 md:grid-cols-[180px_1fr]"><div className="rounded-lg border bg-white p-3"><QRCodeSVG value={setup.otpauthUrl} size={150}/></div><div><p className="text-sm">Scan this QR code in Google Authenticator, Microsoft Authenticator, 1Password or another compatible app.</p><p className="mt-2 break-all rounded bg-slate-100 p-2 font-mono text-xs">{setup.secret}</p><input value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,""))} maxLength="6" inputMode="numeric" className="mt-3 w-full rounded-lg border px-3 py-2" placeholder="Six-digit code"/><button type="button" disabled={busy||code.length!==6} onClick={()=>run(()=>_post("/api/security/mfa/enable",{code}),"Multi-factor authentication enabled")} className="mt-3 rounded-lg bg-customTextNavy px-4 py-2 text-white disabled:opacity-50">Verify and enable</button></div></div>}
  </section>
  <section className="mt-6"><div className="flex items-center justify-between"><h3 className="font-semibold">Signed-in devices</h3><button type="button" disabled={busy} onClick={()=>run(()=>_post("/api/security/sessions/revoke-others",{}),"Other sessions revoked")} className="rounded border px-3 py-2 text-sm">Sign out other devices</button></div><div className="mt-3 divide-y rounded-xl border">{sessions.map(s=><div key={s.id} className="flex items-center justify-between gap-4 p-4"><div><strong>{s.deviceName||"Unknown device"}{s.current?" (this device)":""}</strong><p className="text-xs text-slate-500">Last active {new Date(s.lastSeenAt).toLocaleString()} · {s.ipAddress||"IP unavailable"}</p></div>{!s.current&&<button type="button" onClick={()=>run(()=>_delete(`/api/security/sessions/${s.id}`),"Device signed out")} className="text-sm text-red-700">Sign out</button>}</div>)}</div></section>
 </div>;
}
