import { useState } from "react";
import { ArrowLeft, Building2, CheckCircle2 } from "lucide-react";
import { _post } from "../../utils/ApiService";
import { showError } from "../../utils/toaster";
import BusinessLocationFields from "../../components/Address/BusinessLocationFields";

const initial = { firstName:"", lastName:"", email:"", phone:"", businessName:"", legalName:"", businessType:"HOME_CARE", registrationNumber:"", website:"", addressLine1:"", addressLine2:"", city:"", state:"", country:"United Kingdom", countryCode:"GB", timezone:Intl.DateTimeFormat().resolvedOptions().timeZone || "Europe/London", postcode:"", acceptTerms:false };
const Field = ({label, name, form, setForm, type="text", required=false, placeholder=""}) => <label className="block text-left text-sm font-medium text-gray-700">{label}{required && <span className="text-red-500"> *</span>}<input type={type} required={required} value={form[name]} placeholder={placeholder} onChange={e=>setForm({...form,[name]:e.target.value})} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm focus:border-customBlue focus:outline-none" /></label>;

export default function RegisterBusiness({setActiveComponent,setEmail}) {
  const [form,setForm]=useState(initial), [busy,setBusy]=useState(false), [complete,setComplete]=useState(false);
  const submit=async e=>{e.preventDefault();setBusy(true);try{await _post("/api/auth/register-business",form);setEmail(form.email);setComplete(true);}catch(error){showError(error?.response?.data?.message||"Registration could not be completed.");}finally{setBusy(false);}};
  if(complete) return <div className="flex min-h-screen items-center justify-center bg-customNavy px-4 font-poppins"><div className="w-full max-w-lg rounded-2xl bg-white p-10 text-center shadow-xl"><CheckCircle2 className="mx-auto h-14 w-14 text-green-600"/><h1 className="mt-4 text-2xl font-bold text-customTextGrey1">Application submitted</h1><p className="mt-3 text-sm text-gray-600"><b>{form.businessName}</b> is awaiting approval from a Caremonitor platform administrator. We sent a branded confirmation to <b>{form.email}</b> and will email a secure dashboard link after approval.</p><button onClick={()=>setActiveComponent("Login")} className="mt-6 rounded-lg bg-customBlue px-6 py-2.5 font-semibold text-white">Back to sign in</button></div></div>;
  return <div className="min-h-screen bg-customNavy px-4 py-10 font-poppins" style={{backgroundImage:"url('/login-bg.svg')"}}><form onSubmit={submit} className="mx-auto w-full max-w-3xl rounded-2xl bg-white p-6 shadow-xl md:p-10"><button type="button" onClick={()=>setActiveComponent("Login")} className="mb-5 flex items-center gap-2 text-sm text-gray-600 hover:text-gray-900"><ArrowLeft size={17}/>Back to sign in</button><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-3 text-customBlue"><Building2/></div><div><h1 className="text-2xl font-bold text-customTextGrey1">Create your care business</h1><p className="text-sm text-gray-500">Set up your secure organisation workspace.</p></div></div>
  <h2 className="mb-3 mt-7 border-b pb-2 font-semibold text-gray-800">Business owner</h2><div className="grid gap-4 md:grid-cols-2"><Field label="First name" name="firstName" form={form} setForm={setForm} required/><Field label="Last name" name="lastName" form={form} setForm={setForm} required/><Field label="Work email" name="email" type="email" form={form} setForm={setForm} required/><Field label="Phone number" name="phone" type="tel" form={form} setForm={setForm} required/></div>
  <h2 className="mb-3 mt-7 border-b pb-2 font-semibold text-gray-800">Organisation</h2><div className="grid gap-4 md:grid-cols-2"><Field label="Business name" name="businessName" form={form} setForm={setForm} required/><Field label="Legal name" name="legalName" form={form} setForm={setForm}/><label className="block text-left text-sm font-medium text-gray-700">Service type *<select value={form.businessType} onChange={e=>setForm({...form,businessType:e.target.value})} className="mt-1 w-full rounded-lg border border-gray-300 px-3 py-2.5"><option value="HOME_CARE">Home care</option><option value="LIVE_IN_CARE">Live-in care</option><option value="SUPPORTED_LIVING">Supported living</option><option value="CARE_HOME">Care home</option><option value="OTHER">Other</option></select></label><Field label="Registration number" name="registrationNumber" form={form} setForm={setForm} placeholder="CQC or local regulator (optional)"/><Field label="Website" name="website" type="url" form={form} setForm={setForm}/></div>
  <h2 className="mb-3 mt-7 border-b pb-2 font-semibold text-gray-800">Business address</h2><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><Field label="Address line 1" name="addressLine1" form={form} setForm={setForm} required/></div><Field label="Address line 2" name="addressLine2" form={form} setForm={setForm}/><BusinessLocationFields form={form} setForm={setForm}/></div>
  <label className="mt-6 flex items-start gap-3 text-sm text-gray-600"><input type="checkbox" required checked={form.acceptTerms} onChange={e=>setForm({...form,acceptTerms:e.target.checked})} className="mt-1"/><span>I confirm I am authorised to create this organisation and agree to the Terms of Service and Privacy Policy.</span></label><button disabled={busy} className="mt-6 w-full rounded-lg bg-customBlue py-3 font-semibold text-white disabled:opacity-60">{busy?"Creating your workspace…":"Create business account"}</button><p className="mt-4 text-center text-xs text-gray-500">Your account is isolated from other organisations and protected by email verification.</p></form></div>;
}
